# Generated by Django 3.1 on 2021-03-30 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20210330_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sub_url',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
