# Generated by Django 3.1 on 2021-04-04 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_vulnlist_sub_first'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vulnlist',
            name='sub_first',
        ),
        migrations.AddField(
            model_name='vulnlist',
            name='detect_date',
            field=models.DateField(auto_now=True),
        ),
    ]
