# Generated by Django 3.1 on 2021-05-11 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210405_0047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='sub_first',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sub_second',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='sub_third',
            field=models.DateField(null=True),
        ),
    ]
